// packages/ruta_vue/route_matches.vue
<script lang="ts">
export const ROUTER_SYMBOL = Symbol();
export const ROUTE_SYMBOL = Symbol();
const DEPTH_SYMBOL: InjectionKey<number> = Symbol();
</script>

<script setup lang="ts">
import { computed, inject, provide, type InjectionKey } from 'vue';
import { use_route } from './mod.js';
import RouteMatches from './route_matches.vue';

const route = use_route();
const index = inject(DEPTH_SYMBOL, 0);

const component = computed(() => route.pages[index]);
const has_children = computed(() => route.pages.length > index);

provide(DEPTH_SYMBOL, index + 1);
</script>

<template>
	<component v-if="component" :is="component">
		<RouteMatches v-if="has_children" />
	</component>
</template>

// packages/ruta_svelte/route_matches.svelte
<script context="module">
	export const ROUTER_SYMBOL = Symbol();
	export const ROUTE_SYMBOL = Symbol();
	const DEPTH_SYMBOL = Symbol();
</script>

<script>
	import { getContext, setContext } from 'svelte';
	import { get_route } from './mod.js';

	const route = get_route();
	const index = getContext(DEPTH_SYMBOL) || 0;

	$: component = $route.pages[index];
	$: has_children = $route.pages.length > index;

	setContext(DEPTH_SYMBOL, index + 1);
</script>

{#if component}
	<!-- Due to how slot is implemented in Svelte, we have to wrap the whole block https://github.com/sveltejs/svelte/issues/6325 -->
	{#if has_children}
		<svelte:component this={component}>
			<svelte:self />
		</svelte:component>
	{:else}
		<svelte:component this={component}></svelte:component>
	{/if}
{/if}
