// playground/solid/src/routes/root_layout.tsx
import { use_router } from 'ruta-solid';
import { ParentProps } from 'solid-js';

export default function root_layout(props: ParentProps) {
	const router = use_router();

	return (
		<>
			<h1>root layout {Date.now()}</h1>

			<a href={router.to_href('/')}>index</a>
			<a href={router.to_href('/home')}>home</a>
			<a
				href={router.to_href({
					path: '/params/:param_id',
					params: {
						param_id: 123,
					},
				})}
			>
				params/123
			</a>

			{props.children}
		</>
	);
}

// playground/vue/src/routes/root_layout.vue
<script setup lang="ts">
import { use_router } from 'ruta-vue';

const router = use_router();
</script>

<template>
	<h1>root layout {{ Date.now() }}</h1>

	<a :href="router.to_href('/home')">home</a>
	<a
		:href="
			router.to_href({
				path: '/params/:param_id',
				params: {
					param_id: 123,
				},
			})
		"
		>123</a
	>
	<a
		:href="
			router.to_href({
				path: '/params/:param_id',
				params: {
					param_id: 456,
				},
			})
		"
		>456</a
	>

	<slot />
</template>
